### ISSUE TITLE
Open Soundbar window on launch

### ISSUE THREAD

**Issue by pavelmacek** [pavelmacek/soundbar#19]
When launching the app, the soundbar window should open.

**Comment by DEGoodmanWilson** [comment]
This one turns out to be damned hard for a sandboxed app. Which this must be, to sell it on the app store. It is totally possible, of course, but I'm struggling with it. Watch this space.

**Comment by pavelmacek** [comment]
Man, freaking sand boxing. I would normally say lets do it in v2 somewhere in the future, but for a menubar app it's fairly important it starts after startup, because it's hard to find it as it doesn't sit in the dock :/ Anyway, we'll do what we can :)

**Comment by pavelmacek** [comment]
I think this one is done, yay!
