### ISSUE TITLE
Make corners of menubar round

### ISSUE THREAD

**Issue by pavelmacek** [pavelmacek/soundbar#6]
– Make webview transparent
– Make webview respect rounded corners
– Inject CSS (round corners) to a Souncloud auth page during OAuth

**Comment by pavelmacek** [comment]
We will have to make the corners of menubar rounder in native code, we can't do it with CSS because we have no control of soundcloud auth page styles (can't give it round corners).

**Comment by DEGoodmanWilson** [comment]
Dammit, just not sure how to fix this.

**Comment by DEGoodmanWilson** [comment]
wantsLayer. Of course. Fixed in ad39223594d8f22859dd31ebeb934c44009bc704

**Comment by DEGoodmanWilson** [comment]
Notice that the rounded corners must be set in code—the webView does not pay any attention to the CSS inside! So, no need to inject any CSS, I hope!
