### ISSUE TITLE
Menubar UI (Stream and Like) is flickering when scrolling

### ISSUE THREAD

**Issue by pavelmacek** [pavelmacek/soundbar#8]
Right after lunch of the menubar (without switching to a different app), scrolling in Stream and Likes makes the UI flicker.

**Comment by pavelmacek** [comment]
This is extremely annoying, as it happens with random intensity, sometimes only when quickly scrolling, sometimes a lot even with slow scrolling.

**Comment by DEGoodmanWilson** [comment]
Done by moving to WKWebView
